#!/bin/bash

# Branch Protection Setup Script for Photo2ProfitAI
# This script provides the commands needed to set up branch protection rules
# Run these commands using GitHub CLI (gh) or via GitHub web interface

echo "🔒 Setting up branch protection rules for Photo2ProfitAI"
echo "=================================================="
echo ""

# Check if GitHub CLI is installed
if command -v gh &> /dev/null; then
    echo "✅ GitHub CLI detected. You can run these commands directly:"
    echo ""
    
    # Main branch protection
    echo "🛡️  Setting up main branch protection..."
    echo "gh api repos/:owner/:repo/branches/main/protection \\"
    echo "  --method PUT \\"
    echo "  --field required_status_checks='{\"strict\":true,\"contexts\":[\"Basic Validation\",\"Security Scan\"]}' \\"
    echo "  --field enforce_admins=false \\"
    echo "  --field required_pull_request_reviews='{\"required_approving_review_count\":1,\"dismiss_stale_reviews\":true,\"require_code_owner_reviews\":true}' \\"
    echo "  --field restrictions=null"
    echo ""
    
    echo "🤖 Setting up Copilot agent rules..."
    echo "gh api repos/:owner/:repo/branches/main/protection \\"
    echo "  --method PATCH \\"
    echo "  --field required_status_checks='{\"strict\":true,\"contexts\":[\"Basic Validation\",\"Security Scan\",\"Copilot Agent Validation\"]}'"
    echo ""
    
else
    echo "ℹ️  GitHub CLI not found. Please install it or use the GitHub web interface."
    echo "   Install: https://cli.github.com/"
    echo ""
fi

echo "📋 Branch Protection Rules to Configure:"
echo "========================================"
echo ""
echo "🎯 Main Branch Protection:"
echo "  ✅ Require pull request reviews (1 approval minimum)"
echo "  ✅ Require code owner reviews (CODEOWNERS file)"
echo "  ✅ Dismiss stale reviews when new commits are pushed"
echo "  ✅ Require status checks to pass before merging:"
echo "     - Basic Validation"
echo "     - Security Scan"
echo "     - Copilot Agent Validation (for agent PRs)"
echo "  ✅ Require branches to be up to date before merging"
echo "  ✅ Include administrators in restrictions: NO"
echo "  ✅ Allow force pushes: NO"
echo "  ✅ Allow deletions: NO"
echo ""

echo "🌐 Manual Setup via GitHub Web Interface:"
echo "========================================"
echo "1. Go to: https://github.com/selfishthangs-ux/photo2profitai/settings/branches"
echo "2. Click 'Add rule' for branch 'main'"
echo "3. Configure the following settings:"
echo ""
echo "   📋 Branch Protection Settings:"
echo "   ☑️  Require a pull request before merging"
echo "   ☑️  Require approvals (1)"
echo "   ☑️  Dismiss stale pull request approvals when new commits are pushed"
echo "   ☑️  Require review from code owners"
echo "   ☑️  Require status checks to pass before merging"
echo "   ☑️  Require branches to be up to date before merging"
echo "   ☑️  Require conversation resolution before merging"
echo ""
echo "   🔍 Required Status Checks (add these):"
echo "   - Basic Validation"
echo "   - Security Scan"
echo "   - Copilot Agent Validation"
echo ""
echo "   🚫 Restrictions:"
echo "   ☑️  Restrict pushes that create files in this branch"
echo "   ☐  Include administrators (leave unchecked for flexibility)"
echo "   ☑️  Do not allow bypassing the above settings"
echo ""

echo "🤖 Additional Copilot Agent Settings:"
echo "===================================="
echo "After initial setup, consider these enhancements:"
echo ""
echo "1. 🏷️  Auto-labeling for agent PRs:"
echo "   - Add GitHub Action to auto-label PRs from copilot/* branches"
echo "   - Labels: 'copilot-agent', 'auto-generated'"
echo ""
echo "2. 📧 Notification settings:"
echo "   - Set up notifications for agent PR reviews"
echo "   - Configure weekly digest of agent activity"
echo ""
echo "3. 📊 Monitoring:"
echo "   - Track agent PR success rate"
echo "   - Monitor code quality metrics"
echo "   - Review agent behavior weekly"
echo ""

echo "🔧 Additional Security Enhancements:"
echo "==================================="
echo "1. Enable Dependabot:"
echo "   - Go to Security tab > Dependabot alerts"
echo "   - Enable dependency updates"
echo ""
echo "2. Enable CodeQL scanning:"
echo "   - Go to Security tab > Code scanning"
echo "   - Set up CodeQL analysis"
echo ""
echo "3. Enable secret scanning:"
echo "   - Automatically enabled for public repos"
echo "   - Configure for private repos if needed"
echo ""

echo "✅ Verification Steps:"
echo "===================="
echo "After setup, verify by:"
echo "1. Creating a test PR to main branch"
echo "2. Confirming required checks appear"
echo "3. Testing that merging is blocked without approval"
echo "4. Verifying CODEOWNERS reviewers are automatically assigned"
echo ""

echo "🎉 Setup Complete!"
echo "=================="
echo "Your repository now has comprehensive protection against:"
echo "• Unauthorized direct pushes to main"
echo "• Unreviewed code changes"
echo "• Security vulnerabilities"
echo "• Copilot agent policy violations"
echo ""
echo "For questions or issues, refer to:"
echo "• CONTRIBUTING.md"
echo "• .github/COPILOT_CODING_AGENT.md"
echo "• GitHub docs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository"