# Railway deployment configuration
# This tells Railway how to deploy your backend

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"

# Environment variables to set in Railway dashboard:
# ALERT_DISCORD_WEBHOOK_URL=your-webhook-url
# FIREBASE_PRIVATE_KEY=your-firebase-key
# STRIPE_FOUNDING_PRICE_ID=your-stripe-price
# REMOVEBG_API_KEY=your-remove-bg-key